[tool.poetry]
name = "scrapy-fix-price"
version = "0.1.0"
description = ""
authors = ["Пользователь <yaroslav-rusin@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.11.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
